/**
 *  JayCompiler it a class that show how a scanner generated by JFlex
 *  is running. This scanner produces instances of the class Token
 *  @see Token 
 */

package co.edu.eafit.dis.st0270.jaycompiler;

import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import co.edu.eafit.dis.st0270.jaycompiler.jflex.JayCompilerLexer;
import co.edu.eafit.dis.st0270.jaycompiler.tokens.Token;
import co.edu.eafit.dis.st0270.jaycompiler.parser.JayParserManual;
import co.edu.eafit.dis.st0270.jaycompiler.ast.Program;

public class JayCompilerManual {

    private static void usage(int errcode) {
        System.err.println("Usage: java CompilerJay <file>");
        System.exit(errcode);
    }

    /**
     * This method starts a class.
     * <p>
     * @param args It accepts only one file name. This filename is used to show
     *             how the an scanner generated by JFlex is running.
     * 
     */
    public static void main(String args[]) {

	if (args.length != 1) {
	    usage(1);
	}

	InputStreamReader isr = null;
	try {
	    isr = new InputStreamReader(new FileInputStream(args[0]));
	}
	catch (FileNotFoundException fnfe) {
	    System.err.println(fnfe);
	    usage(2);
	}

	try {
	    JayCompilerLexer lexer = new JayCompilerLexer(isr);

	    JayParserManual jpm = new JayParserManual(lexer);

	    Program astPrg = jpm.program();
	}
	catch (Exception e) {
	    System.err.println(e);
	    System.exit(3);
	}
    }
}
