
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ExprMemSymbols {
  /* terminals */
  public static final int RECALL = 8;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int ADD = 3;
  public static final int STORE = 7;
  public static final int SUB = 4;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int TIMES = 5;
  public static final int LPAREN = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "ADD",
  "SUB",
  "TIMES",
  "DIV",
  "STORE",
  "RECALL",
  "LPAREN",
  "RPAREN"
  };
}

