
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class DyckParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return DyckSymbols.class;
}

  /** Default constructor. */
  @Deprecated
  public DyckParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public DyckParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public DyckParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\005\000\002\003\005\000\002\003\006" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\012\000\004\004\005\001\002\000\004\002\014\001" +
    "\002\000\006\004\005\005\007\001\002\000\004\002\000" +
    "\001\002\000\010\002\uffff\004\005\005\uffff\001\002\000" +
    "\004\005\011\001\002\000\010\002\ufffe\004\005\005\ufffe" +
    "\001\002\000\006\002\ufffc\005\ufffc\001\002\000\006\002" +
    "\ufffd\005\ufffd\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\012\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\004\003\007\001\001\000\002\001\001\000\004" +
    "\003\012\001\001\000\002\001\001\000\004\003\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$DyckParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$DyckParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$DyckParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$DyckParser$actions {
  private final DyckParser parser;

  /** Constructor */
  CUP$DyckParser$actions(DyckParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$DyckParser$do_action_part00000000(
    int                        CUP$DyckParser$act_num,
    java_cup.runtime.lr_parser CUP$DyckParser$parser,
    java.util.Stack            CUP$DyckParser$stack,
    int                        CUP$DyckParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$DyckParser$result;

      /* select the action based on the action number */
      switch (CUP$DyckParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-1)).value;
		RESULT = start_val;
              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-1)), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$DyckParser$parser.done_parsing();
          return CUP$DyckParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= dyck 
            {
              Object RESULT =null;

              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          return CUP$DyckParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // dyck ::= LPAREN RPAREN 
            {
              Object RESULT =null;

              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("dyck",1, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-1)), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          return CUP$DyckParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // dyck ::= LPAREN dyck RPAREN 
            {
              Object RESULT =null;

              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("dyck",1, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-2)), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          return CUP$DyckParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // dyck ::= LPAREN RPAREN dyck 
            {
              Object RESULT =null;

              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("dyck",1, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-2)), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          return CUP$DyckParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // dyck ::= LPAREN dyck RPAREN dyck 
            {
              Object RESULT =null;

              CUP$DyckParser$result = parser.getSymbolFactory().newSymbol("dyck",1, ((java_cup.runtime.Symbol)CUP$DyckParser$stack.elementAt(CUP$DyckParser$top-3)), ((java_cup.runtime.Symbol)CUP$DyckParser$stack.peek()), RESULT);
            }
          return CUP$DyckParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$DyckParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$DyckParser$do_action(
    int                        CUP$DyckParser$act_num,
    java_cup.runtime.lr_parser CUP$DyckParser$parser,
    java.util.Stack            CUP$DyckParser$stack,
    int                        CUP$DyckParser$top)
    throws java.lang.Exception
    {
              return CUP$DyckParser$do_action_part00000000(
                               CUP$DyckParser$act_num,
                               CUP$DyckParser$parser,
                               CUP$DyckParser$stack,
                               CUP$DyckParser$top);
    }
}

}
